[DEFAULT]
# 10-20 channel plotting order
CHANNEL_ORDER = ['Fp2','Fpz','Fp1','AF8','AF4','AFz','AF3','AF7','F8','F6','F4','F2','Fz','F1','F3','F5','F7','FT8','FC6','FC4','FC2','FCz','FC1','FC3','FC5','FT7','T8','C6','C4','C2','Cz','C1','C3','C5','T7','TP8','CP6','CP4','CP2','CPz','CP1','CP3','CP5','TP7','P10','P8','P6','P4','P2','Pz','P1','P3','P5','P7','P9','PO8','PO4','POz','PO3','PO7','O2','Oz','O1','Iz']

[PATHS]
# location of data file(s), may be a single file or a directory containing multiple files
DATA = "path\\to\\your\\data"

# directory where results should be stored (directory, NOT a file)
SAVE = "path\\to\\results\\directory"

[CONDITION_STIMULI]
# add one line for each condition in the following format:
# condition_name = [stimulus marker 1 , stimulus marker 2 , ...]
ambi_after_EE = [103, 104, 105, 106, 107]    
ambi_after_EU = [203, 204, 205, 206, 207]

[MNE]
# MNE data import arguments
# see https://mne.tools/stable/generated/mne.io.read_raw_brainvision.html#mne.io.read_raw_brainvision
IMPORT_ARGS = { eog = ['Up', 'Down', 'Left', 'Right'], misc = 'auto', scale = 1.0 }

# List of reference electrode names (leave as empty list if not present in data)
ELECTRODES.REFERENCE = ['M1', 'M2']

# List electrode names that should be ignored
ELECTRODES.BAD = []

# Electrodes to plot the ERP of, as a preliminary check. 
# Leave empty to plot all channels.
ELECTRODES.ERP_CHECK = ['Fz', 'Cz', 'Pz']

# Starting/ending times of trials in seconds 
# (if baseline segment should be included, starting time can be negative)
T_MIN = -0.2
T_MAX = 1.0

# Resampling parameters (STRONGLY RECOMMENDED TO RESAMPLE)   
# For resampling approach see https://mne.tools/stable/auto_tutorials/preprocessing/30_filtering_resampling.html#resampling
# Frequency to downsample to. Reduces computational load of decoding procedure.
RESAMPLE.FREQUENCY = 100

# At what point should resampling occur? (choose 'raw', 'epoch', or 'do_not_resample')
RESAMPLE.METHOD = 'epoch'

[DECODING]
# See https://scikit-learn.org/stable/modules/classes.html#module-sklearn.linear_model
# or  https://scikit-learn.org/stable/modules/classes.html#module-sklearn.svm

# random state seed
RAND_STATE = 1

# Available methods: OLS, LogRes, Ridge, SVC, SVM
MODEL = 'LogRes'
MODEL_ARGS = { class_weight = 'balanced' }

# available classification scoring methods: 
# https://scikit-learn.org/stable/modules/model_evaluation.html
SCORING = 'roc_auc'
SCORING_ARGS = { }

# no. of cross-validation folds to use
CROSS_VAL_FOLDS = 5

# no. of jobs to run in parallel. If -1, equal to number of CPU cores
N_JOBS = -1
